-------------------ESTE SCRIPT SE HA CREADO PARA LLEVAR CONTROL DE LAS FUNCIONES SQL QUE DEBEN SER EJECUTADAS DENTRO DE LA BASE DE DATOS INTEGRACION_REPLICA
-- PARA SU FUNCIONAMIENTO DENTRO DEL CENTRO DE RESULTADOS

-------------------CREACION DE SERVIDOR REMOTO PARA EXPORTAR TABLAS DE INTEGRACION--------------------
-- En ambas bases de datos
CREATE EXTENSION IF NOT EXISTS postgres_fdw;

---------------------FUNCION PARA OBTENER LAS COMPETENCIAS CONSUMO TOTAL DE INTEGRACION_REPLICA-------------------------------

CREATE OR REPLACE FUNCTION "INTEGRACION".obtenerCompetencias(course VARCHAR)
RETURNS VOID AS
$$
BEGIN
-- Crear la tabla temporal
CREATE TEMPORARY TABLE tablaTempComp(
"CMP_ID" BIGINT,
"CMP_NOMBRE" VARCHAR,
"CMP_ACTIVO" VARCHAR,
"CMP_CODIGO" BIGINT,
"FIC_ID" BIGINT
);

-- Insertar los datos en la tabla temporal
INSERT INTO tablaTempComp("CMP_ID", "CMP_NOMBRE", "CMP_ACTIVO", "CMP_CODIGO", "FIC_ID")

select c2."CMP_ID", c2."CMP_NOMBRE", c2."CMP_ACTIVO", c2."CMP_CODIGO", fic."FIC_ID"
from "INTEGRACION"."V_FICHA_CARACTERIZACION_B" fic
join "INTEGRACION"."V_PROGRAMA_FORMACION_B" prf on fic."PRF_ID" = prf."PRF_ID"
join "INTEGRACION"."COMPETENCIAXPROGRAMA" c on c."PRF_ID" = prf."PRF_ID"
join "INTEGRACION"."COMPETENCIA" c2 on c2."CMP_ID" = c."CMP_ID"
WHERE fic."FIC_ID" = course::BIGINT AND c2."CMP_ACTIVO" = '1';


-- Crear la vista a partir de la tabla temporal
CREATE OR REPLACE VIEW vista_com AS
SELECT * FROM tablaTempComp;
END;
$$
LANGUAGE 'plpgsql';

